---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age183lzztp2t7cfztlaqkgykrhlvsnph5pczvdgeay56wpn8hnr2ceqlluhjq"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age183lzztp2t7cfztlaqkgykrhlvsnph5pczvdgeay56wpn8hnr2ceqlluhjq"
stores:
  yaml:
    indent: 2
