apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:CiQgBZ7+M19dh+mM5Hlzr3d5WhZtb25/N4Qf7qdPj9zQvPve,iv:2fGdnJo0Ofgnku9R9ww0IehlKqi7YiHVbxYzOxi9Qj4=,tag:KbNGiYHUOdYMxN2UW7aCdw==,type:str]
    credentials.json: ENC[AES256_GCM,data:iQwOz/yzWuk7yBytkIOMLNkI+de/SNv8xN34F9DEyZnCy4Rdr2hqLrGn6+CVCLrIIgvdgV0ODNgs9yrbM/R/2OCQ37hCayms7EznO6wMjcHHLI3LjcjxOYrWpZAvI3bmdS1VRJyWT1oklei0awQz1ZMo0z0oetLIzA76d5fEQS+8sRlVW+w7NzhRkmkZYZbbAoYxhOihxG0wdjO6XfgN6eN/HhluCpbQ3I+t/Dx0Sw==,iv:fvSyOeI6JlOpFwO4co4hF48PiT2rPdar8aBWqq+HCsg=,tag:CtQ3DcevNRgcC8fBO4UF2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekg8qhs84jadwh2e3f3cuescyku96knc6rezymz64nvyr9f854fqcvf2zl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NHIycVRyOWxPYytaRzZu
            NFlCQWlvRy9Ka0JWZWlWa05xcGJmMFdvTkRvCkJZdmdOYm1ZelhBSlI3YU5Ka0JI
            NVFWZEJnVVdXMkJWZTFYOWwyZUlXTjgKLS0tIG1GL3huS25ZUzdDeDhDZDZPb25K
            M05acXZZTDNBdVF5VDJEcC9ET0lTdDQKRRu3qes9AptsTQNbLXNzJfr/vRDyDQDA
            6tqwiyg0AkGitGKsKOsAoizQ3KtXImxVLA2DGHe2qx1os+3ok4y/yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T08:54:17Z"
    mac: ENC[AES256_GCM,data:PudbkhzklSi9LkStkeHS1nAerSC2hSbH1lBnqllLB41t+uSa53F5BpvFpOTIBvZ8QyC8kggok/RNaB12XpvVi5CO4BE0ogBNoHKUEDfz4Fivgv30QYfRn/N9yTN1bqnoScBqiXhjjcOMYkGzchnhboTo1qlf7svr96JYHre8iH0=,iv:QafymwV5G7gC400Odt2DhwaRNv70dxTUvxTnZNHtjcY=,tag:qN+cXsaIZqNQLjJRFjTYkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
