apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:EA0ufs79/8eFD/44JrjydkDgV6PitBLnNcHPBVKmOS+pNh+i,iv:UTVg3tS28Ek5TrLHRyoAAug52Ysnc1gVPE5uHA89rWI=,tag:OAXpxNSoPyP9lYT1ZHYtlQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:SZ5sTLcZYJ6E1GHdkGOIvFp+nbwlTU90hnmkAJQKR6xUf2qyP4klLi6lzzUPRFe9wW4ctDYyZtuaaSSjqQ7d2CorVgZXBxJzetHpx4nVzSmBV4JYB58coph5ELqSXl62BQagPpkzPLdNUV1OwaaQ+fZkdD/mwuj7SNeN+ja92Uv3F2LJZbslutjEIZCDhMI7s2kAcmomsaPnqI/W6IfXCwt2Z1LYt4O4zulbYUUY3g==,iv:H7IGpi90H3P9PeIFryitXNj6NKqUsUVpKu1KUf5Jedc=,tag:a3UT1dDz2rrmM5+nmC9YXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c0ummpjkythpwslaqmk2x53fpp566mf6k306434xt24yhg0jrc3q7yx3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWXJSNmF6SHhKMWV4YTk1
            VWlhR3R1dXBmRk1xSGU5eGE3YmJNSWl3blZFCnZQSksrVy92VnJUL0cyZiszcXIv
            WHpIWm5velpXdXFLbUR4NEdFWVJTUmsKLS0tIGYxRWZTWUl1RlRaREpZK01GYXhP
            bW5HSmpldGxLYnhETjRhc1lSMVhUVWcKwQeFheI5O9Cnh08P4/6pwdGZZ9VZ7u3P
            Q0Qwb3fxjFZt0IQJcJDEfow6247i5h0Cr7nGbzLX55tuPMwj3Z5mgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T21:55:14Z"
    mac: ENC[AES256_GCM,data:ZoEcaXLDu3P61wbQya0b+3JrrPnXm8jJb7unJLcO1oHZwYvUEgzYZ04feTR/vjrGT/lKv6ArRIj21V7kOW1VDWL468fH3SDI1KAnSZnC6GUYg12sTPeGm6M5eu16WvPzwz1cFvk9bMAvHBTTcgQLw30SNeMP+ovg3GmaJef7A28=,iv:VPM+01+mwi8GqA5nt5WMZEBKi9M7fAToje9BhjNOGhw=,tag:Q0F+7EQtJeldr1JwcR7+3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
