# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ndq7muwEwWx9U3R5jUUtr9Z7omhe9y+rqfh5qQ54wvg=,iv:2+utUazTMtaUFeQkxYroCU5//kRV289NhMjWowd3quY=,tag:sBI9TdCm5AqLP0WEd1HoSA==,type:str]
sops:
  age:
    - recipient: age183lzztp2t7cfztlaqkgykrhlvsnph5pczvdgeay56wpn8hnr2ceqlluhjq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrODJxY3Fvd0FFTDZKNWtC
        ZHhKaGFSNlVERXB5THBCSWRQeE5BYU82SUU0ClFlWWxwbThySVNwby92MXllenE4
        cWRrbWI3R2psYkNXNG1PSjRtdVgxdEEKLS0tIEhTSFRCUjAwSUtQY1BVc01sa1FY
        bFJDRTA2WlNRUTR6U1ZDbEU1K3JqL28K1cii+mTzc/gCHp5NVKXuLdE3sjMABFCe
        TYFhJs0luoEtTuX0KVVn2M9mtptSa0A3m7zGk2L5PmGaN53/EGe+Rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-20T10:25:22Z"
  mac: ENC[AES256_GCM,data:+axx7IO/bo5okIDqO00ZyDEeo5eVilxdOVu8g7IOjc79ElWlOHx/hc62gSkKUIZsolovO+Pke6u6OrqltUOU7vLeCclv5R4A3F6v3EI5zH9vgjUD/POSgGrcrR2wQVnsR7+W5niNLdHDaUJ5Hj3dIpik55OowcbdXA7n5Ep/iTM=,iv:lI5OaLIsK/gouDeBFcWzpvgA5sew9C3BeXdcOma/90o=,tag:7vqRmEAJ+JSYIFgCLUPPTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
