apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Cj8FJ/quyioIiheFNQFlRcc/3RkmnNRAF9KBuoULFwVnb4AiMfj/PA==,iv:k5EHYEt/XCHQ/denkqgv7gO2tvCzMSr0c6NzyvixuCQ=,tag:LyBgbU7PPzOvqVbdEN12SQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekg8qhs84jadwh2e3f3cuescyku96knc6rezymz64nvyr9f854fqcvf2zl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQSt6WDExcFpycWJyZzUx
            Q0Y3UWJnclFQdG8zRE92QWFLS0hTcWUydGdFCnNCb1BKZ0ZiazRidUg3MmJQOVI4
            ekUxNTRBM2RZdHJGZXA0NkptVjF5amcKLS0tIEliTk5MVEIvSHRHOHZNclg0UTEz
            RzdhVHdiWCt6N2g0dzZFaTNaaGtpVGcKUZbCesT8nRo3ZkU6a0bhfog8zTbU5v8F
            HsznPEobnxhDx/VXRht7S2zIqI4EqIqFUbqKJL3O3SX+z8LNKNI9+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T08:54:17Z"
    mac: ENC[AES256_GCM,data:aEFrFL7Zd73gWTBpModBFDNjF3kkyYVJuAxgkQaqorJcoA1SxuMnphF5mPuk5krw4OviojH556LbXnB+3fNePZGNQKN74RSY6HTJApTQF8PX8otdVl6YSVAxGqIZaxPbZooVMCCCvrcGtHn3x64YqghEpLqui6qER2hxsZOs+bY=,iv:NNox3oCffRtwdZdrk7zmCrIM9v0/zJoNF/z3v46aZv4=,tag:XgIl8XMvIb/BmJ+2Q34N2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
