apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:IpqnnWYtvVTrMdq2guwG+H6c/aEuY/hFe80dfh3aV1Lc2gOma6ZmmA==,iv:EXjrPcG8SOzT8OVcrYKQ9H51Uf/CNkTvMw9giZdc+BQ=,tag:KXAAVXWtq6/RUBWGzPQ7ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c0ummpjkythpwslaqmk2x53fpp566mf6k306434xt24yhg0jrc3q7yx3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRGUwSWJyS0JOd3NnMXp4
            YmNWT1JBV2FKalZ1MTIzNHh4dEp1cE9HNEdJCml3ZVlzTmk5YUw5VkZTanBJZDgw
            TTVSZVowbDBRcUJYRUx1T3VFTXBFL0kKLS0tIDhsMDlUYk14TE0wSXJIQmhFV0Vl
            OEt2SW8yTmc3WVIrc1VwNnZESkdXTG8KtMRM0R9QmIkC3CiQe2oxmTNOGI8Z8N6k
            7hpWvg0wEa+YZRJ7FAlKnPt2cGJYvXfkR6jf4k6WCRlgQ2lRq7UBvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T15:34:56Z"
    mac: ENC[AES256_GCM,data:3oBw8awmVn+J73Gn7tc7qtBPHMof6GetYrR2M/fbyrzY0RBmxj8Uq1XKLzCEyJZogbliqEivF8Yqj/iG0xQOgoVO6xwEGJ1ORq+jILSMLAVoGiOBjno+2emlK2EZPfDjetH+p2/HJF8SP/ZOgW8X5awypJ1uqLnFeljCnD/Myvk=,iv:qyyDkREwrL1ONop+sKBp+ypVKOFmeFkluo5cwXob2w4=,tag:Ou0+nIVU8knl5hlZjYPD3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
