apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:flLSwqq8HrhtvFdk,iv:ReC5beI4GDOFYqdG29wRaPC7/tzMMuuYHK04PAlDRlM=,tag:a1Nx/CmTDAY1ehAV8JTfwg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:BFE0MNdhRTz73qQxRn1UdTFu2BFUxvU=,iv:HWlUM9VA7A9TlYUVYAU7hZHvD+G1GOrPjeHCLldn1Ts=,tag:vI4PzDNyEbhxlsQKo+GFfw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:9EyUKX+B179Lino49c5J1zgF1ep4FOwvuuFZfLj9eo2Cvzm4,iv:vwE4ZLW7ZZdf6CSkp7fsvEe3DgXV2xtc6QDG1LTe7AA=,tag:Q+nWAp8/eJ5YrxY2uFRftg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekg8qhs84jadwh2e3f3cuescyku96knc6rezymz64nvyr9f854fqcvf2zl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaVhaUVd1MEJ2Zk9HVXBk
            WENDNDl2cjFZamdkTTFqZEZWRlMzK3ZqMVhJCmNlNExYVzI3a0lhTW5oM0kzNTVC
            QTVvYituZEJzbjFuMmlkemNLNDhMK2cKLS0tIDBOMXBtbmlLekZkS2F6a2pERnhG
            YjdrQjJKVDNxNU15OGVSZUllckJ1M0UKLbfmWepZvjSbToybZm1WWCCo2w2tyMTj
            80bKww2VH6+jhuMH86zprP+9PlN1Q4bAjLgFjXuvcZRU3nB0wrgX+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T08:54:17Z"
    mac: ENC[AES256_GCM,data:G8U4Hvqq/bkemOlgTQxb2tQMMZvmG8XiDAEup6LeXIzancr6gsR1Jv8QCGygRn07jTaSB1y/cueuv+qSmjFMOFN4wo00iwilpBAr4l1ISs4rjYRjJXB0nHHjyBvRSuHZ8jC//xrckGkIZEO81HzMz01KL2L5EVAyHF3cUjfwDfM=,iv:XyNdiJtQsu3/qPL+pXi5lXnRXK8R/iPCzR+zaQUIDyM=,tag:WkwczFAY0VbZG+WVDjq+Dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
