apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:BPNN6RUxqCcunAy4D3LJq0IZdMfx1hHiVyzMPiaZWRw=,iv:SlAi2CX5C9/jcamwiMWcYfXLY1pxinGnSsQAmh3k8ow=,tag:rAKpp7W684ZZW1bmPWWBbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekg8qhs84jadwh2e3f3cuescyku96knc6rezymz64nvyr9f854fqcvf2zl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWUp0RWl5eWNUNGk3NGtL
            czNqNm1Rb2ZmM25naElVWUZYQmtBb1R2cXhzCnZyUWtHdW1nQ1RBaDhUaVlBaE1i
            RC9NRFBubmJ4MGVPU1NqRXFsekNJS28KLS0tIHREZFZEZzRwaDdXT0M1WkdWRXcz
            dis0L1FCU0lWSTdQeTlvUnpqM09RZHMKmMkMGCXKpovZLmw9MOfsLwm/i1x7Dk5D
            tjlXevhYr6Yiq8i7LudnNQnmKpncR6+xHMe+E77i7g50otKGmtTwzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T08:54:17Z"
    mac: ENC[AES256_GCM,data:9laAnHoatiYkXL53tNrdMJi/WGu5gjvodmZsGk/pq/X5WRvyBPESbZVbQYYJS4Xvzlh4e1Brm7lk7XbOTQytO/bGnWmh/vBnF68nxwrWHpcY3T4H/5dUKX/Ksl20D/VZ0djIJTsYbSdxVeiFkF3w90mixJouJBlglOd3biRKHM0=,iv:tKLABO3gRa4xtKCEY9uphuiFXSyo7xgAW5V0Jn/HECM=,tag:1zfVm0LTfqW2MnR8gZr+Kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
