apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:dG9kZq9ZX/jRaVgtEdEHYg4Mac797aBxC4Yq+jznzn1EM+lKtaflfQ==,iv:wMcHE9dixqWIxz16+f5Mxa9tkiYuk9aOmN7jeohpBMc=,tag:ukyPLIin3XTBSLru0f0TBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekg8qhs84jadwh2e3f3cuescyku96knc6rezymz64nvyr9f854fqcvf2zl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WmVrd0VwZ1lrUmVPMUNU
            a2diRytGM0t6Smw0b3NuRktmci8zRVRjaVZnCkU0K3VKK1Ezc1ZlUlpzN2pRNktX
            eTJvWEVUcEEwcjg4bVMrRUtxV2Z5MDAKLS0tIFEvZjFNVFRUbmRJSWpUWk9sVktI
            Mk5xSTIyeXhXdjhlY1RCOUk2c2JXYUEK6fs9W2qsyptpJojOyr04Yf86Yazy7rqf
            rLu41qfjD3aiL20YopjhFrBb6r5qQiS7Z5bio7vO1oBL0q6uOtHpaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T08:54:17Z"
    mac: ENC[AES256_GCM,data:xqVka4zp9NPwWZnwJBINwaQul8gTTbfYKEVceNbTJTyLvUV1X+RCVQbFvXqIxqIoIBHyJI5paZEdugjgaTgFWKO/uWzWPzlzqeqr6/0fkwbjtmwIVxY7byxbW4ClY04DLWWvHTxyS39s68Cz74jMKUW9i7l27xDzzGFQlrr3jq4=,iv:OuLuOmzS/Cvmp1Clo532VZt3USnK/1ZgJUptacRG6x4=,tag:AEP6BT/8dJAthxJx0yzNSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
