apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:h/B9ZX9aCZceygjw5nNDwfzAwViXrrBYU+vrPR5jSNNMCZeTo2hYzQ==,iv:qv+7txEtTpyYaRMsoR9bDj6Uvs9A17Jgt3V7e/rSDUc=,tag:zOdFgCQEqY1m2vceYpe2mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c0ummpjkythpwslaqmk2x53fpp566mf6k306434xt24yhg0jrc3q7yx3a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeDNXeStRRVBYVncyWExy
            MlpMVUt2OElxMkdUaUwyMVV3OUljWGZ4OTJnCnlReDZhVXlXZit2bjhKWWJSZWJu
            ck9KNXpQNlcvTVNLK21MODRTdkVxUU0KLS0tIEVEanRWT3JOblhJZFNTbU1MVjBI
            b0FlT0VTdDQvSSt5OVBISlhRSFE5QW8KqNlJh43HRUAcY90N/QLLVsmiZG6PFZEi
            dxGqgVn2CmXLNAz7XdmzX6cKSDtEeAdOy256wJfnNWWNrfgQ2HKQrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T15:34:56Z"
    mac: ENC[AES256_GCM,data:XSRqI9E3AZfCFsiavIDCNUXgR4NBHIPrUZswfErEUyqcClLVvYZL+tUyPH6XEpNEz0HqLv9WUdysmf+dXK1DhzLxWEbOCh+UmG/2i7V/GnJCY5h+h65q3UWwGHbSydOHBGkSlSpn8NFBUkF5JKBx6lQpE7jAU7cGpo2da0SvpcQ=,iv:ppRwgpi3l+gCBJB0pvMCz+MzB/xwouLzeAHjWT+qQ50=,tag:g1EhppHoftlE0iO5Uy0E1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
